---
:concurrency: 25
production:
  :concurrency: 25
:timeout: 20
:queues:
  - [user, 40]
  - [critical, 4]
  - [repo_maintenance_stat_high, 25]
  - [mailers, 8]
  - [tree, 6]
  - [repo_maintenance_stat, 4]
  - [default, 10]
  - [small, 20]
  - [score, 3]
  - [status, 2]
  - [issues, 2]
  - [owners, 1]
  - [repo, 2]
  - [sourcerank, 1]
  - [repo_maintenance_stat_low, 1]
